os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -workspace QizzApp/QizzApp.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.4,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
